services:
  db:
    build: .
    container_name: mtcg_test
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"  # Host port : Container port
    volumes:
      - ./CreateDatabase.sql:/docker-entrypoint-initdb.d/CreateDatabase.sql
volumes:
  db_data: